---
- name: Install required packages.
  become: true
  apt:
    update_cache: yes
    name: ['vim', 'git', 'openjdk-8-jre', 'openjdk-8-jdk', 'mysql-client', 'python-mysqldb']
    state: present

- include: setup-docker.yml
  when: ansible_distribution == 'Ubuntu'

- name: Initialize swarm
  ignore_errors: yes
  shell: 'docker swarm init'

- name: Create Application network
  ignore_errors: yes
  shell: 'docker network create -d overlay --attachable app'
