pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git "http://localhost:3001/administrator/techflow-frontend.git"
            }
        }
        stage ('Build Docker Image') {
            steps {
                sh './build.sh $BUILD_NUMBER'
            }
        }
        stage('Upload Artifact') {
            steps {
                sh './publish.sh $BUILD_NUMBER'
            }
        }
        stage('Deploy') {
            steps {
                sh './update_frontend_image.sh $BUILD_NUMBER'
            }
        }
    }
}
